baseURL = 'https://colinwhitten.github.io/'
locale = 'en-us'
title = 'Colin Whittens Bibliography'
theme='shibui'
contentdir = 'content'

[markup]
[markup.highlight]
style = "bw"


[menu]
  [[menu.main]]
    name = "posts"
    url = "/posts/"
    weight = 1


