baseURL = 'https://colinwhitten.github.io/'
locale = 'en-us'
title = 'Colin Whittens Bibliography'
theme='shibui'
contentdir = 'content'

[markup]
[markup.highlight]
style = "bw"


[[menu.header]]
name = "posts"
url = "posts/"
weight = 30

